### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gvisani** [gvisani/hpacker#1]
- [x] Add network trained with partial side-chains for conditional initial guess, add appropriate functions to HPacker
- [ ] Add code to evaluate steric clashes
- [ ] Code and test training procedure using biopython instead of pyrosetta for parsing PDB structures
- [ ] Write readme for training
